name: 🚀 Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to Vultr
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: root
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            cd /var/www/uritisaiabhishek.dev
            ./deploy.sh
